name: Testing Action

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check Eslint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - run: cd frontend
      - run: npm install
      - run: npx eslint '**/*.{ts,tsx}'
      - run: cd ../backend
      - run: npm install
      - run: npx eslint '**/*.{ts}'
  tsc:
    runs-on: ubuntu-latest
    name: Check Typescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
      - run: cd frontend
      - run: npm install
      - run: npm run build
      - run: cd ../backend
      - run: npm install
      - run: npm run build